sonata_media:
    db_driver: doctrine_orm
    default_context: default
    contexts:
        default:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo
                - sonata.media.provider.custom_image

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
        workshop:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 400 , quality: 90}
                big:   { width: 1440 , quality: 90}

    cdn:
        server:
            path: /upload/media

    filesystem:
        local:
            # Directory for uploads should be writable
            directory: "%kernel.project_dir%/public/upload/media"
            create: false

    class:
        media: App\Application\Sonata\MediaBundle\Entity\Media
        gallery: App\Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: App\Application\Sonata\MediaBundle\Entity\GalleryHasMedia

    providers:
        image:
            resizer: sonata.media.resizer.square
