version: '3.3'

services:
  php-fpm:
    #user: "${UID-www-data}:${GID-www-data}"
    image: exozet/php-fpm:7.2-sudo
    env_file:
      - ./.docker/common.env
      - ./.env
    depends_on:
      - mysql
    ports:
      - '9000'
    volumes:
      - ./:/usr/src/app
      - ./var/log/php:/var/log/php
      - ./.docker/php/config/php.ini:/usr/local/etc/php/php.ini:ro
    working_dir: /usr/src/app
  nginx:
    image: nginx:1.14-alpine
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    volumes:
      - ./:/usr/src/app:ro
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
  mysql:
    image: mysql:5.6.35
    env_file:
      - ./.docker/common.env
      - ./.env
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./.docker/mysql/mysql.cnf:/etc/mysql/conf.d/docker.cnf
    ports:
      - "3306:3306"
