# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

gallery:
  resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
  prefix: /media/gallery

media:
  resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
  prefix: /media
